apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  database-url: "postgresql://username:password@postgres:5432/plnts"
  postgres-user: "postgres"
  postgres-password: "admin"